name: Generate photos.json

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "photos/**"
      - "tools/generate-photos-json.js"
      - "package.json"

permissions:
  contents: write

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm run gen

      - name: Commit photos.json if changed
        run: |
          if git diff --quiet -- photos.json; then
            echo "No changes to photos.json"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add photos.json
          git commit -m "Auto-update photos.json"
          git push
